// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.soon.socket.pb;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageEnumOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code MessageEnum}
   */
  public static final class MessageEnum extends
      com.google.protobuf.GeneratedMessage
      implements MessageEnumOrBuilder {
    // Use MessageEnum.newBuilder() to construct.
    private MessageEnum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageEnum(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageEnum defaultInstance;
    public static MessageEnum getDefaultInstance() {
      return defaultInstance;
    }

    public MessageEnum getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageEnum(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.soon.socket.pb.Message.internal_static_MessageEnum_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.soon.socket.pb.Message.internal_static_MessageEnum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.soon.socket.pb.Message.MessageEnum.class, com.soon.socket.pb.Message.MessageEnum.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageEnum> PARSER =
        new com.google.protobuf.AbstractParser<MessageEnum>() {
      public MessageEnum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageEnum(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageEnum> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MessageEnum.ClientMsg}
     *
     * <pre>
     *1 - 4999
     * </pre>
     */
    public enum ClientMsg
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>C_LoginGame = 1;</code>
       */
      C_LoginGame(0, 1),
      ;

      /**
       * <code>C_LoginGame = 1;</code>
       */
      public static final int C_LoginGame_VALUE = 1;


      public final int getNumber() { return value; }

      public static ClientMsg valueOf(int value) {
        switch (value) {
          case 1: return C_LoginGame;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ClientMsg>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ClientMsg>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ClientMsg>() {
              public ClientMsg findValueByNumber(int number) {
                return ClientMsg.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.soon.socket.pb.Message.MessageEnum.getDescriptor().getEnumTypes().get(0);
      }

      private static final ClientMsg[] VALUES = values();

      public static ClientMsg valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ClientMsg(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageEnum.ClientMsg)
    }

    /**
     * Protobuf enum {@code MessageEnum.StrategyMsg}
     *
     * <pre>
     *5000 - 5999
     * </pre>
     */
    public enum StrategyMsg
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>S_LoginGame = 5000;</code>
       */
      S_LoginGame(0, 5000),
      ;

      /**
       * <code>S_LoginGame = 5000;</code>
       */
      public static final int S_LoginGame_VALUE = 5000;


      public final int getNumber() { return value; }

      public static StrategyMsg valueOf(int value) {
        switch (value) {
          case 5000: return S_LoginGame;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StrategyMsg>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StrategyMsg>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StrategyMsg>() {
              public StrategyMsg findValueByNumber(int number) {
                return StrategyMsg.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.soon.socket.pb.Message.MessageEnum.getDescriptor().getEnumTypes().get(1);
      }

      private static final StrategyMsg[] VALUES = values();

      public static StrategyMsg valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private StrategyMsg(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageEnum.StrategyMsg)
    }

    /**
     * Protobuf enum {@code MessageEnum.GlobalMsg}
     *
     * <pre>
     *6000 - 6499
     * </pre>
     */
    public enum GlobalMsg
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>G_LoginGame = 6000;</code>
       */
      G_LoginGame(0, 6000),
      ;

      /**
       * <code>G_LoginGame = 6000;</code>
       */
      public static final int G_LoginGame_VALUE = 6000;


      public final int getNumber() { return value; }

      public static GlobalMsg valueOf(int value) {
        switch (value) {
          case 6000: return G_LoginGame;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<GlobalMsg>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<GlobalMsg>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<GlobalMsg>() {
              public GlobalMsg findValueByNumber(int number) {
                return GlobalMsg.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.soon.socket.pb.Message.MessageEnum.getDescriptor().getEnumTypes().get(2);
      }

      private static final GlobalMsg[] VALUES = values();

      public static GlobalMsg valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private GlobalMsg(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageEnum.GlobalMsg)
    }

    /**
     * Protobuf enum {@code MessageEnum.RouteMsg}
     *
     * <pre>
     *6500 - 6999
     * </pre>
     */
    public enum RouteMsg
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>R_LoginGame = 6500;</code>
       */
      R_LoginGame(0, 6500),
      ;

      /**
       * <code>R_LoginGame = 6500;</code>
       */
      public static final int R_LoginGame_VALUE = 6500;


      public final int getNumber() { return value; }

      public static RouteMsg valueOf(int value) {
        switch (value) {
          case 6500: return R_LoginGame;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RouteMsg>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RouteMsg>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RouteMsg>() {
              public RouteMsg findValueByNumber(int number) {
                return RouteMsg.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.soon.socket.pb.Message.MessageEnum.getDescriptor().getEnumTypes().get(3);
      }

      private static final RouteMsg[] VALUES = values();

      public static RouteMsg valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RouteMsg(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageEnum.RouteMsg)
    }

    /**
     * Protobuf enum {@code MessageEnum.BattleMsg}
     *
     * <pre>
     *7000 - 7499
     * </pre>
     */
    public enum BattleMsg
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>B_LoginGame = 7000;</code>
       */
      B_LoginGame(0, 7000),
      ;

      /**
       * <code>B_LoginGame = 7000;</code>
       */
      public static final int B_LoginGame_VALUE = 7000;


      public final int getNumber() { return value; }

      public static BattleMsg valueOf(int value) {
        switch (value) {
          case 7000: return B_LoginGame;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BattleMsg>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BattleMsg>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BattleMsg>() {
              public BattleMsg findValueByNumber(int number) {
                return BattleMsg.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.soon.socket.pb.Message.MessageEnum.getDescriptor().getEnumTypes().get(4);
      }

      private static final BattleMsg[] VALUES = values();

      public static BattleMsg valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private BattleMsg(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageEnum.BattleMsg)
    }

    /**
     * Protobuf enum {@code MessageEnum.CrossMsg}
     *
     * <pre>
     *7500 - 7999
     * </pre>
     */
    public enum CrossMsg
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CR_LoginGame = 7500;</code>
       */
      CR_LoginGame(0, 7500),
      ;

      /**
       * <code>CR_LoginGame = 7500;</code>
       */
      public static final int CR_LoginGame_VALUE = 7500;


      public final int getNumber() { return value; }

      public static CrossMsg valueOf(int value) {
        switch (value) {
          case 7500: return CR_LoginGame;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CrossMsg>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CrossMsg>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CrossMsg>() {
              public CrossMsg findValueByNumber(int number) {
                return CrossMsg.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.soon.socket.pb.Message.MessageEnum.getDescriptor().getEnumTypes().get(5);
      }

      private static final CrossMsg[] VALUES = values();

      public static CrossMsg valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CrossMsg(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageEnum.CrossMsg)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.soon.socket.pb.Message.MessageEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.soon.socket.pb.Message.MessageEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.soon.socket.pb.Message.MessageEnum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageEnum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.soon.socket.pb.Message.MessageEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.soon.socket.pb.Message.internal_static_MessageEnum_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.soon.socket.pb.Message.internal_static_MessageEnum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.soon.socket.pb.Message.MessageEnum.class, com.soon.socket.pb.Message.MessageEnum.Builder.class);
      }

      // Construct using com.soon.socket.pb.Message.MessageEnum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.soon.socket.pb.Message.internal_static_MessageEnum_descriptor;
      }

      public com.soon.socket.pb.Message.MessageEnum getDefaultInstanceForType() {
        return com.soon.socket.pb.Message.MessageEnum.getDefaultInstance();
      }

      public com.soon.socket.pb.Message.MessageEnum build() {
        com.soon.socket.pb.Message.MessageEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.soon.socket.pb.Message.MessageEnum buildPartial() {
        com.soon.socket.pb.Message.MessageEnum result = new com.soon.socket.pb.Message.MessageEnum(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.soon.socket.pb.Message.MessageEnum) {
          return mergeFrom((com.soon.socket.pb.Message.MessageEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.soon.socket.pb.Message.MessageEnum other) {
        if (other == com.soon.socket.pb.Message.MessageEnum.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.soon.socket.pb.Message.MessageEnum parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.soon.socket.pb.Message.MessageEnum) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MessageEnum)
    }

    static {
      defaultInstance = new MessageEnum(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MessageEnum)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageEnum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"\307\001\n\013MessageEnum\"\034\n\tClien" +
      "tMsg\022\017\n\013C_LoginGame\020\001\"\037\n\013StrategyMsg\022\020\n\013" +
      "S_LoginGame\020\210\'\"\035\n\tGlobalMsg\022\020\n\013G_LoginGa" +
      "me\020\360.\"\034\n\010RouteMsg\022\020\n\013R_LoginGame\020\3442\"\035\n\tB" +
      "attleMsg\022\020\n\013B_LoginGame\020\3306\"\035\n\010CrossMsg\022\021" +
      "\n\014CR_LoginGame\020\314:B\035\n\022com.soon.socket.pbB" +
      "\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MessageEnum_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MessageEnum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageEnum_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
